nav:
    - Concurrency-control: index.md 
    - Optimistic-and-pessimistic: Optimistic-and-pessimistic.md
    - Synchronization: Synchronization.md
    - Concurrency-control: Concurrency-control.md
    - Mutual-exclusion: Mutual-exclusion.md
    - Lock: Lock
    
    
    
    - Software-transactional-memory: Software-transactional-memory

    
    - Read-copy-update: Read-copy-update
