nav:
    - Introduction: index.md 
    
    - Synchronization: Synchronization
    - How-to-optimize: How-to-optimize
    - Challenge: Challenge
    
    - Optimistic-and-pessimistic: Optimistic-and-pessimistic
    
    - Mutual-exclusion: Mutual-exclusion
    
    - Transactional-memory: Transactional-memory
    
    - Non-blocking: Non-blocking
    
    - Barrier: Barrier
