nav:
    - Synchronization: Synchronization.md
    - Concurrency-control: Concurrency-control.md
    - Mutual-exclusion: Mutual-exclusion.md
    - Lock: Lock
    
    
    nav:
    - Concurrency-control: index.md
    
    - Multiversion-concurrency-control: Multiversion-concurrency-control.md
    - Optimistic-and-pessimistic: Optimistic-and-pessimistic.md
    
    - Read-copy-update: Read-copy-update.md
    - Compare-and-swap: Compare-and-swap.md
    - Fetch-and-add: Fetch-and-add.md