nav:
    - Introduction: index.md 
    - Synchronization: Synchronization
    - Challenge: Challenge
    - Linearizability: Linearizability    
    - Optimistic-and-pessimistic: Optimistic-and-pessimistic
    - Mutual-exclusion: Mutual-exclusion
    - Transactional-memory: Transactional-memory
    - Non-blocking: Non-blocking
    - Barrier: Barrier
