nav:
    - Introduction: index.md 
    - Challenge: Challenge
    - Optimistic-and-pessimistic: Optimistic-and-pessimistic
    - Synchronization: Synchronization.md
    - Concurrency-control: Concurrency-control.md
    - Mutual-exclusion: Mutual-exclusion.md
    - Lock: Lock
    - Transactional-memory: Transactional-memory
    - Read-copy-update: Read-copy-update
    - Barrier: Barrier
