nav:
    - Introduction: index.md 
    - TODO-Mutex: TODO-Mutex
    - Linux-Seqlock: Linux-Seqlock
    - Read–write-lock: Read–write-lock
    - Spinlock: Spinlock
    - Double-checked-locking: Double-checked-locking    
    - TODO-Hand-over-hand-lock: TODO-Hand-over-hand-lock
    
    - Disadvantage: Disadvantage
    - Granularity-of-lock: Granularity-of-lock
    - Evaluation-metric: Evaluation-metric