nav:
    - Introduction: index.md 
    
    - Synchronization: Synchronization
    - Lock: Lock
    - Barrier: Barrier    
    - Non-blocking: Non-blocking    
    - Transactional-memory: Transactional-memory    
   
    - Optimistic-and-pessimistic: Optimistic-and-pessimistic
    - Non-blocking-VS-blocking: Non-blocking-VS-blocking
    