nav:
    - Introduction: index.md

    - Stream-based-message-processing-system: Stream-based-message-processing-system
    - Distributed-log-system: Distributed-log-system
    - Messaging-pattern: Messaging-pattern
    - library-ZeroMQ: library-ZeroMQ