nav:
    - Introduction: index.md
    - 01-Locks-Aren't-Slow-Lock-Contention-Is: 01-Locks-Aren't-Slow-Lock-Contention-Is
    - 02-Always-Use-a-Lightweight-Mutex: 02-Always-Use-a-Lightweight-Mutex
    - 03-A-C++Profiling-Module-for-Multithreaded-APIs: 03-A-C++Profiling-Module-for-Multithreaded-APIs
    - 04-A-Look-Back-at-Single-Threaded-CPU-Performance: 04-A-Look-Back-at-Single-Threaded-CPU-Performance
    - 05-Roll-Your-Own-Lightweight-Mutex: 05-Roll-Your-Own-Lightweight-Mutex
    - 06-Implementing-a-Recursive-Mutex: 06-Implementing-a-Recursive-Mutex
    - 07-Lightweight In-Memory Logging: 07-Lightweight In-Memory Logging