nav:
    - Introduction: index.md
    - Client–server-architecture: Client–server-architecture
    - Peer-to-peer-architecture: Peer-to-peer-architecture
    - Shared-nothing-architecture: Shared-nothing-architecture
