nav:
    - Introduction: index.md
    - Client–server-architecture: Client–server-architecture.md
    - Peer-to-peer-architecture: Peer-to-peer-architecture
    - Client-server-VS-Peer-to-peer: Client-server-VS-Peer-to-peer.md