nav:
    - Introduction: index.md
    - Messaging-pattern: Messaging-pattern.md
    - Pub-sub: Pub-sub
    - Actor-proactor-reactor: Actor-proactor-reactor
    - Message-queue: Message-queue
    - drdobbs-Message-Handling-Without-Dependencies: drdobbs-Message-Handling-Without-Dependencies