nav:
    - Introduction: index.md 
    - TODO-Mutex: TODO-Mutex
    - Linux-Seqlock: Linux-Seqlock
    - Read–write-lock: Read–write-lock
    - Spinlock: Spinlock
    - Double-checked-locking: Double-checked-locking    
    - TODO-Optimistic-and-pessimistic: TODO-Optimistic-and-pessimistic
    - Disadvantage: Disadvantage
    - Evaluation-metric-for-lock: Evaluation-metric-for-lock    