nav:
    - Introduction: index.md 
    - TODO-Mutex: TODO-Mutex
    - Linux-Seqlock: Linux-Seqlock
    - Read–write-lock: Read–write-lock
    - Spinlock: Spinlock
    - Double-checked-locking: Double-checked-locking    

    - Disadvantage: Disadvantage
    - Evaluation-metric: Evaluation-metric