nav:
    - Introduction: index.md

    - Parallel-numeric-processing-system: Parallel-numeric-processing-system
    - Data-system: Data-system
    - Blockchain: Blockchain
    - IPFS: IPFS


    - NFS: NFS
    - RPC: RPC