nav:
    - Introduction: index.md
    - mariusbancila-Dining-philosopher: mariusbancila-Dining-philosopher
    - TODO-howardhinnant-Dining-Philosophers-Rebooted: TODO-howardhinnant-Dining-Philosophers-Rebooted