nav:
    - Introduction: index.md
    - library-syscpp: library-syscpp
    - rosettacode-Active-object: rosettacode-Active-object.md
    - kjellhedstrom2-Active-Object-the-C++11-way: kjellhedstrom2-Active-Object-the-C++11-way