nav:
    - Introduction: index.md
    - Expert-Leslie-Lamport: Expert-Leslie-Lamport    
    - Expert-Dr-Werner-Vogels: Expert-Dr-Werner-Vogels
    - Expert-Martin-Kleppmann: Expert-Martin-Kleppmann
    - Course: Course
    - Book-Designing-Data-Intensive-Applications: Book-Designing-Data-Intensive-Applications
    - Book-Distributed-systems-for-fun-and-profit: Book-Distributed-systems-for-fun-and-profit
    - dist-prog-book: dist-prog-book
    - Guide: Guide
    - Theory: Theory
    - Technique: Technique
    - Architecture: Architecture