nav:
    - Introduction: index.md
    - Expert-Leslie-Lamport: Expert-Leslie-Lamport    
    - Book-Designing-Data-Intensive-Applications: Book-Designing-Data-Intensive-Applications
    - Book-Distributed-operating-systems: book-Distributed-operating-systems    
    - Book-Programming-Models-for-Distributed-Computing: Book-Programming-Models-for-Distributed-Computing
    # - Book-Distributed-systems-for-fun-and-profit: Book-Distributed-systems-for-fun-and-profit
    - martinfowler-Patterns-of-Distributed-Systems: martinfowler-Patterns-of-Distributed-Systems
    - Theory: Theory
    - Technique: Technique
    - Architecture: Architecture

    