nav:
    - Distributed-computing: index.md
    - Book-Designing-Data-Intensive-Applications: Book-Designing-Data-Intensive-Applications
    - Book-Distributed-operating-systems: book-Distributed-operating-systems    
    - Book-Programming-Models-for-Distributed-Computing: Book-Programming-Models-for-Distributed-Computing
    # - Book-Distributed-systems-for-fun-and-profit: Book-Distributed-systems-for-fun-and-profit
    - Theory: Theory
    - Technique: Technique
    - Architecture: Architecture
    - Expert-Leslie-Lamport: Expert-Leslie-Lamport
    - Distributed-hash-table: Distributed-hash-table