nav:
    - Distributed-computing: index.md
    - Theory: Theory
    - Technique: Technique
    - Architecture: Architecture
    - Expert-Leslie-Lamport: Expert-Leslie-Lamport
    - Distributed-hash-table: Distributed-hash-table