nav:
    - Introduction: index.md
    - wikipedia-Logical-clock: wikipedia-Logical-clock
    - Lamport-timestamp: Lamport-timestamp
    - Happened-before: Happened-before
    - scattered-thoughts-Causal-ordering: scattered-thoughts-Causal-ordering