nav:
#################### 建立一个统一的模型来描述parallel computing####################
    - Model: Model.md
#################### fork-join model是一种非常普遍的model####################     
    - Fork–join-model: Fork–join-model.md
#################### promise-future是一种非常普遍的model####################         
    - Promise-future: Promise-future
    - Actor-proactor-reactor: Actor-proactor-reactor