nav:
    - Introduction: index.md
    - The-Trouble-with-Distributed-Systems: The-Trouble-with-Distributed-Systems.md
    - Book-Designing-Data-Intensive-Applications: Book-Designing-Data-Intensive-Applications
    - Book-Distributed-systems-for-fun-and-profit: Book-Distributed-systems-for-fun-and-profit
    - Abstraction: Abstraction
    - CAP: CAP
    - High-availability: High-availability
    - Consensus: Consensus
    - Partitioning: Partitioning
    - Replication: Replication
    - Logical-clock: Logical-clock