nav:
    - Book-Designing-Data-Intensive-Applications: Book-Designing-Data-Intensive-Applications
    - Consensus: Consensus
    - High-availability: High-availability
    - Logical-clock: Logical-clock