nav:
    - Introduction: index.md
    - Distributed-system-challenge: Distributed-system-challenge
    - Abstraction: Abstraction    
    - Design-goal-of-distributed-systems: Design-goal-of-distributed-systems.md
    - Byzantine-Fault-Tolerance: Byzantine-Fault-Tolerance
    # - Book-Distributed-systems-for-fun-and-profit: Book-Distributed-systems-for-fun-and-profit

    - CAP: CAP
    - Consistency: Consistency
    - High-availability: High-availability    
    - Network-partition: Network-partition

    - Consensus: Consensus
    - Partitioning: Partitioning
    - Replication: Replication
    - Logical-clock: Logical-clock