nav:
    - Introduction: index.md
    - Distributed-system-challenge: Distributed-system-challenge
    - Abstraction: Abstraction    
    - Design-goal-of-distributed-systems: Design-goal-of-distributed-systems.md
    
    # - Book-Distributed-systems-for-fun-and-profit: Book-Distributed-systems-for-fun-and-profit

    - CAP: CAP
    - High-availability: High-availability
    - Consensus: Consensus
    - Partitioning: Partitioning
    - Replication: Replication
    - Logical-clock: Logical-clock