nav:
    - Introduction: index.md
    - Distributed-system-challenge: Distributed-system-challenge
    - Abstraction: Abstraction    
    - CAP: CAP # CAP
    - Consistency: Consistency # CAP 的 C
    - High-availability: High-availability # CAP 的 A
    - Network-partition: Network-partition # CAP 的 P   
    - Fault-tolerance: Fault-tolerance
    - Consensus: Consensus
    - Logical-clock: Logical-clock
    - Protocol: Protocol
    - Split-brain: Split-brain # 它是有network partition引发的