nav:
    - Introduction: index.md 
    - CAP: CAP # CAP
    - Consistency-model: Consistency-model # CAP 的 C
    - High-availability: High-availability # CAP 的 A
    - Network-partition: Network-partition # CAP 的 P   
    - Fault-tolerance: Fault-tolerance
    - Consensus: Consensus
    - Time&Ordering: Time&Ordering
    - Protocol: Protocol
    - Split-brain: Split-brain # 它是有network partition引发的
    