nav:
    - Introduction: index.md
    - wikipedia-Logical-clock: wikipedia-Logical-clock
    - Lamport-timestamp: Lamport-timestamp
    - Happened-before: Happened-before
    - Vector-clock: Vector-clock
    - Version-vector: Version-vector