nav:
    - Introduction: index.md
    - Spinning-lock-optimization: Spinning-lock-optimization.md
    - rochester-paper-Spinlock-with-timeout: rochester-paper-Spinlock-with-timeout
    - Ticket-lock: Ticket-lock