nav:
    - Introduction: index.md
    - Spinning-lock-optimization: Spinning-lock-optimization
    - paper-Algorithms-for-Scalable-Synchronization: paper-Algorithms-for-Scalable-Synchronization
    - paper-Spinlock-with-timeout: paper-Spinlock-with-timeout
    - Ticket-lock: Ticket-lock
    - library-geidav-spinlocks-bench: library-geidav-spinlocks-bench
    - library-honkiko-Multi-Core-Toolbox: library-honkiko-Multi-Core-Toolbox
    - library-bogachevdmitry-CLHLock: library-bogachevdmitry-CLHLock