nav:
    - Introduction: index.md
    - Asynchronous-method-dispatch: Asynchronous-method-dispatch.md    
    - Observer-pattern: Observer-pattern
    - Active-object+observer+visitor: Active-object+observer+visitor
    - Proactor-reactor: Proactor-reactor
    - Actor&&active-object: Actor&&active-object
    - Master-worker: Master-worker