nav:
    - Course-disco.ethz-Distributed-Systems: Course-disco.ethz-Distributed-Systems
    - Course-Northeastern-University-CS7680: Course-Northeastern-University-CS7680
    - Course-Rutgers-Distributed-Systems: Course-Rutgers-Distributed-Systems
    