nav:
    - Introduction: index.md
    - Producer–consumer-problem: Producer–consumer-problem
    - Dining-philosophers-problem: Dining-philosophers-problem
    - Readers–writers-problem: Readers–writers-problem

    - Checkpoint-Synchronization: Checkpoint-Synchronization
    - Sleeping-barber-problem: Sleeping-barber-problem
    - Cigarette-smokers-problem: Cigarette-smokers-problem