nav:
    - Introduction: index.md
    # 理论知识
    - TODO-Level-of-free: TODO-Level-of-free
    # 入门指导
    - Primer: Primer
    # memory相关
    - Atomic-operation: Atomic-operation
    - Memory-barrier: Memory-barrier
    
    - Copy-on-write: Copy-on-write
    - Memory-reclamation: Memory-reclamation    
    # 一些技巧
    - Version-based: Version-based


