nav:
    - Introduction: index.md
    - paper-Time-Clocks-and-the-Ordering-of-Events-in-a-Distributed-System: paper-Time-Clocks-and-the-Ordering-of-Events-in-a-Distributed-System
    - towardsdatascience-Understanding-Lamport-Timestamps: towardsdatascience-Understanding-Lamport-Timestamps
    