nav:
    - Concurrent-computing: index.md
    # 专家和经典书籍
    - Books: Books.md
    - Expert-Jeff-Preshing: Expert-Jeff-Preshing    
    - Expert-iter_zc: Expert-iter_zc
    - Expert-1024cores: Expert-1024cores
    - Expert-Cameron: Expert-Cameron
    - Course-tau-Multiprocessor-Programming: Course-tau-Multiprocessor-Programming
    - Course-rochester-Algorithms-for-Scalable-Synchronization-on-Shared-Memory-Multiprocessors: Course-rochester-Algorithms-for-Scalable-Synchronization-on-Shared-Memory-Multiprocessors
    - Course-uhcl-Concurrency: Course-uhcl-Concurrency
    # 先描述 理论知识
    - Concurrency-control: Concurrency-control

    # 总结经典问题
    - Classic-problem: Classic-problem
    # 描述具体application
    - Concurrent-data-structure: Concurrent-data-structure


    # 最最典型的concurrency模式   
    - Multithread: Multithread
