nav:
    - Introduction: index.md
    - TODO-Mutex: TODO-Mutex
    - Seqlock: Seqlock
    - Read–write-lock: Read–write-lock
    - Spinlock: Spinlock
    - Double-checked-locking: Double-checked-locking    
    - Disadvantage: Disadvantage
    - Evaluation-metric-for-lock: Evaluation-metric-for-lock