nav:
    - Home: index.md
    - Parallel-computing: Parallel-computing.md
    - Concurrent-computing: Concurrent-computing
    - Distributed-computing: Distributed-computing
    - Model: Model
    - Programming-model: Programming-model

    - Miscellaneous: Miscellaneous
    - Event-driven-concurrent-server: Event-driven-concurrent-server
    - Message-processing-system: Message-processing-system
    - Application: Application    