nav:
    - Home: index.md
    - Parallel-computing: wikipedia-Parallel-computing.md
    - Synchronization: Synchronization
    - Model: Model
    - Concurrent-computing: Concurrent-computing
    - Distributed-computing: Distributed-computing