nav:
    - Introduction: index.md
    - paper-In-Search-of-an-Understandable-Consensus-Algorithm: paper-In-Search-of-an-Understandable-Consensus-Algorithm    
    - github-The-Raft-Consensus-Algorithm: github-The-Raft-Consensus-Algorithm    
    - wikipedia-Raft: wikipedia-Raft


    